### ISSUE TITLE
Support for other changelog formats?

### ISSUE THREAD

**Issue by rstacruz** [MoOx/github-release-from-changelog#1]
How about supporting other headings (eg, `##`) and linking in versions?

ie: https://github.com/rstacruz/onmount/blob/master/HISTORY.md

**Comment by MoOx** [comment]
Sure. That's a good idea.
First we probably need to add minimal unit testing. I just opened an issue https://github.com/MoOx/github-release-from-changelog/issues/2

**Comment by sapegin** [comment]
And other file names.

**Comment by MoOx** [comment]
PR welcome :)

**Comment by koppor** [comment]
@rstacruz Could you change your changelog format to the one of [Keep a changelog](http://keepachangelog.com/en/1.0.0/)? Then with PR #11 the format would be supported.

**Comment by koppor** [comment]
@sapegin Your issue is recorded at https://github.com/MoOx/github-release-from-changelog/issues/6. As current workaround, you can use `--filename your-custom-filename.md`. I think this should be sufficient to solve your request, isn't it?

**Comment by sapegin** [comment]
@koppor It was two years ago ;-)

**Comment by MoOx** [comment]
Closing in favor of more granular issues.
