### ISSUE TITLE
Bad credentials error

### ISSUE THREAD

**Issue by okonet** [MoOx/github-release-from-changelog#10]
I've added `GITHUB_TOKEN` to my `.zshrc` but still getting this then running in `postpublish` script:

```
.../node_modules/github-release-from-changelog/github-release-from-changelog.js:112
    throw err
    ^
Error: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

**Comment by MoOx** [comment]
Did you restart your shell to get the update?

**Comment by okonet** [comment]
Sure, otherwise it would be `GITHUB_TOKEN must be set` or similar

**Comment by MoOx** [comment]
According to the message, this means that your token don't have the appropriate right to make the intended action (so actually cut the release from the tag).

(and just in case, I didn't cut a release for several days so not sure if there is an api change from github).

**Comment by okonet** [comment]
What rights are required? I gave all for the repo.

**Comment by MoOx** [comment]
Not sure. Maybe incorrectly typed your token or something.
Did you use this technique https://github.com/MoOx/npmpub#requirements ?

**Comment by okonet** [comment]
Kind of. I'm just doing `export GITHUB_TOKEN=...` in my `.zshrc` so seems like API has changed in meantime?

**Comment by MoOx** [comment]
This is not very probable.
Will see next time I will cut a release, maybe tomorrow morning.
Meanwhile, try to regenerate a token?

**Comment by okonet** [comment]
Ok thanks. Will do.

**Comment by MoOx** [comment]
I just cut multiples releases on multiples projects using this module (via npmpub) without any issue.
So your token or the way you insert it in your env is probably wrong.

**Comment by okonet** [comment]
So, after setting it up with npmpub and regenerating the token I can confirm that it works. Awesome job! Thanks! 💯
