### ISSUE TITLE
Monorepo support?

### ISSUE THREAD

**Issue by imcuttle** [MoOx/github-release-from-changelog#26]
```
root/
  packages/
      a/
          CHANGELOG.md
      b/
          CHANGELOG.md
```

**Comment by imcuttle** [comment]
Released https://github.com/imcuttle/gh-release-changelog for resolving it

**Comment by MoOx** [comment]
Running the command from the package folder was enough.

**Comment by imcuttle** [comment]
> Running the command from the package folder was enough.

Sometimes, monorepo would release multi-packages together.
```bash
packages/
    a/
        CHANGELOG.md
    b/
        CHANGELOG.md
```
